# Copyright (c) F5, Inc.
#
# This source code is licensed under the Apache License, Version 2.0 license found in the
# LICENSE file in the root directory of this source tree.

- hosts: agent
  become: yes
  collections:
    - nginxinc.nginx_core
  tasks:
    - name: 'Install Debian pre-requisite packages'
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: true
        state: present
      when: ansible_os_family == "Debian"
      loop:
        - gpg
    - name: Include the nginx role
      include_role:
        name: nginx
